server:
  port: 10001
spring:
  application:
    name: productservice
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.66.0.66:3306/easydb?useSSL=false
      username: root
      password: abc123
      max-active: 200
#      max-idle: 8
      initial-size: 5
      min-idle: 3
  redis:
    host: 172.66.0.66
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 1ms
        max-idle: 8
        min-idle: 0
#    cluster:
#      nodes:
#        - 172.66.0.66:7001
#        - 172.66.0.66:7002
#        - 172.66.0.66:7003
#        - 172.66.0.66:8001
#        - 172.66.0.66:8002
#        - 172.66.0.66:8003
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.easymall.pojo

#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.easymall.pojo

eureka:
  client:
    service-url:
      defaultZone:
        - http://localhost:8761/eureka
        - http://localhost:8762/eureka
