server:
  port: 9005
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: # 路由
        - id: productservice # 路由标识，必须唯一
          uri: lb://productservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/gateway-product/**
        - id: picservice
          uri: lb://picservice
          predicates:
            - Path=/gateway-pic/**
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/gateway-user/**
        - id: cartservice
          uri: lb://cartservice
          predicates:
            - Path=/gateway-cart/**
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/gateway-order/**
      default-filters: # 全局过滤器
        - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone:
        - http://localhost:8761/eureka
        - http://localhost:8762/eureka
