spring:
  rabbitmq:
    host: 172.19.229.202
    port: 5672
    username: root
    password: abc123
    virtual-host: /
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.19.229.202:3306/seckill?useSSL=false
      username: root
      password: abc123
