server:
  port: 10006
spring:
  application:
    name: seckillservice
  rabbitmq:
    host: 172.19.229.202
    port: 5672
    username: root
    password: abc123
    virtual-host: /
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.19.229.202:3306/seckill?useSSL=false
      username: root
      password: abc123
  redis:
    host: 172.19.229.202
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 1ms
        max-idle: 8
        min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
eureka:
  client:
    service-url:
      defaultZone:
        - http://localhost:8761/eureka
        - http://localhost:8762/eureka
